Gh 1005 skills
lambdaclass/mirra_backend pull request #1007
Opened 2024-12-11 22:42 UTC by tvillegas98

## Motivation

*Explain why not how.*
Closes #issue_number

## Summary of changes

*List your changes here.*

## How to test it?

*You can explain how you tested it or suggest a way to do so.*

## Checklist
- [ ] Tested the changes locally.
- [ ] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2025-01-02 19:55 UTC, manucamejo approved these changes

2025-01-03 20:12 UTC, Nico-Sanchez requested changes
Nice work tom!

Since we're making this behavior more complex, we should take our time to document our functions properly. Maybe adding a brief general documentation about the current state machine / behavior of the bots.

2025-01-03 20:12 UTC, Nico-Sanchez commented on apps/bot_manager/lib/bot_state_machine.ex
> +        ran_away(bot_player, game_state, bot_state_machine)
isn't this run_away? this function makes the bot run in the opposite direction, right?

2025-01-03 20:12 UTC, Nico-Sanchez commented on apps/bot_manager/lib/bot_state_machine.ex
> +            |> Map.put(:progress_for_ultimate_skill, bot_state_machine.progress_for_ultimate_skill + 1)
What's this progress about?

2025-01-03 20:12 UTC, Nico-Sanchez commented on apps/bot_manager/lib/bot_state_machine_checker.ex
> +    # The bot state, these are the possible states: [:idling, :moving, :aggresive, :running_away]
Not important. But maybe we can change :aggresive to :attacking to match the other verbs.

2025-01-06 14:35 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine.ex
> +            end
Sure! It would look better

2025-01-06 14:36 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine.ex
> +  end
Yes, I forgot to move this magic number to a variable, thanks

2025-01-06 15:02 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine.ex
> +        Vector.rotate_by_degrees(closest_player.direction, 180) |> Vector.normalize() |> Vector.rotate_by_degrees(180)
Whoops, this is ain't rotating 🤣

2025-01-06 15:12 UTC, tvillegas98 commented on apps/bot_manager/lib/game_socket_handler.ex
> +    Process.send_after(self(), :unblock_attack, Enum.random(500..1000))
Sure! I'll write a documentation about the stuff we did here!

2025-01-06 15:12 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine.ex
> +        ran_away(bot_player, game_state, bot_state_machine)
yes! I'll rename it

2025-01-06 15:16 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine_checker.ex
> +    # The bot state, these are the possible states: [:idling, :moving, :aggresive, :running_away]
Sure!

2025-01-06 15:34 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine.ex
> +    end
I've read this again and did not make sense, I'll change it to directly switch the direction

2025-01-06 16:31 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine.ex
> +            |> Map.put(:progress_for_ultimate_skill, bot_state_machine.progress_for_ultimate_skill + 1)
Oh this is progress is used to make the bots somehow accumulate energy to use a skill, it is just a gimmick. Same for the ultimate

2025-01-06 20:34 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine.ex
> +    do: %{action: :stand, bot_state_machine: bot_state_machine}
I've changed this to `:idling` to make it consistent with other verbs

2025-01-06 20:35 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine.ex
> +            end
Done in [refactor: move code block to maybe_aim_to_a_player/2](https://github.com/lambdaclass/mirra_backend/pull/1007/commits/b2fcf8ef1d8a996300c0f92f48af018e7812f712)

2025-01-06 20:35 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine.ex
> +  end
done in [refactor: use module attribute instead of magic number](https://github.com/lambdaclass/mirra_backend/pull/1007/commits/a64de546e914a29aeff9dcd3632f5dc411cba72d)

2025-01-06 20:36 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine.ex
> +    end
I've changed this on [feat: add new function switch direction and remove the switch based on position](https://github.com/lambdaclass/mirra_backend/pull/1007/commits/efded0681277fca75cecbf41f92295837b52f803)

2025-01-06 20:36 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine.ex
> +        Vector.rotate_by_degrees(closest_player.direction, 180) |> Vector.normalize() |> Vector.rotate_by_degrees(180)
Removed it!

2025-01-07 14:05 UTC, Nico-Sanchez commented on apps/bot_manager/lib/bot_state_machine_checker.ex
> +    health_percentage <= @low_leath_percentage
What does `leath` mean?

2025-01-07 14:05 UTC, Nico-Sanchez approved these changes

2025-01-07 14:10 UTC, tvillegas98 commented on apps/bot_manager/lib/bot_state_machine_checker.ex
> +    health_percentage <= @low_leath_percentage
that means nothing 😆 . It is health

2025-01-07 14:20 UTC, Nico-Sanchez approved these changes

2025-01-08 17:48 UTC, manucamejo approved these changes

2025-01-08 17:48 UTC, merged