Create new settings version table
lambdaclass/mirra_backend pull request #1013
Opened 2024-12-19 15:52 UTC by Nico-Sanchez

## Motivation

*Explain why not how.*
Closes #issue_number

## Summary of changes

*List your changes here.*

## How to test it?

*You can explain how you tested it or suggest a way to do so.*

## Checklist
- [ ] Tested the changes locally.
- [ ] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2025-01-03 21:45 UTC, tvillegas98 requested changes
Great work Nico!! Although the PR is big, it adds a lot of things that were needed for the configurator. 
Regarding the UX for the version creation and the problem it has now, probably we should make the user create the things in the order we want to, for example, if Characters depends on Skills, lets set the skills first then the characters later, so we can use the updated skills from these version and not the previous one 😄. We can address it in another PR

2025-01-06 14:56 UTC, Nico-Sanchez commented on apps/game_backend/lib/game_backend/configuration/version.ex
> +    |> cast_assoc(:game_configuration, with: &GameConfiguration.assoc_changeset/2)
As we discussed at the office, we'll address this in the future.
We might want to "soft-delete" a version and re-use that name. Also, the feature is quite lax for now, we can modify everything and move to any version.
After we use it, we'll know better how to make this feature more secure and restrictive in a useful way to our needs.

2025-01-06 18:28 UTC, tvillegas98 approved these changes

2025-01-06 18:35 UTC, manucamejo approved these changes

2025-01-06 18:35 UTC, merged