Add new apps to umbrella
lambdaclass/mirra_backend pull request #185
Opened 2024-01-23 18:09 UTC by lotuuu

2024-01-23 18:22 UTC, manucamejo requested changes

2024-01-23 18:22 UTC, manucamejo commented on Makefile
> +	docker-compose up -d
Please, use `docker compose` instead of `docker-compose`

2024-01-25 18:03 UTC, manucamejo commented on Makefile
>  	cd apps/game_client && docker compose up -d
We should delete this line as well
And also the `game_client` ecto config

2024-01-25 20:55 UTC, AminArria commented on .tool-versions
> +elixir 1.16.0-otp-26
If you are changing versions here we should also change the CI at least

2024-01-25 21:39 UTC, jrchatruc commented
Overall looks good to me, though when running `make start` I get the following error
```
You have configured application :arena in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :arena exists or remove the configuration.
```

and
 
```
18:25:58.990 [error] Postgrex.Protocol (#PID<0.458.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5433): connection refused - :econnrefused
```

even though I have setup the db with `docker compose up`.

I think the `README` needs to be updated a bit to explain how to setup everything and how to use it/run a simple example.

2024-01-26 15:26 UTC, igaray requested changes

2024-01-26 16:11 UTC, lotuuu commented on apps/champions_of_mirra/README.md
> +**TODO: Add description**
READMEs for applications have been added! Let me know what you think

2024-01-26 16:11 UTC, lotuuu commented on apps/champions_of_mirra/lib/champions_of_mirra.ex
> +  Champions of Mirra request handler. Receives messages from the Gateway app and
I see the terms used were not the best. I've updated the moduledoc now, let me know if you find it clearer

2024-01-26 18:41 UTC, jrchatruc approved these changes

2024-02-02 22:15 UTC, juanbono submitted a review, later dismissed

2024-02-08 16:07 UTC, manucamejo approved these changes

2024-02-08 20:44 UTC, juanbono approved these changes

2024-02-08 22:03 UTC, merged