Cooldown mechanisms
lambdaclass/mirra_backend pull request #378
Opened 2024-03-14 19:22 UTC by AminArria

We introduce a new field for skills called `cooldown_mechanism` which (for now) can be one of two values
- `time` the cooldown is based on time since last execution, this time is read from `cooldown_ms` field. When a skill has this mechanism it will not use stamina or anything related to that
- `stamina` their is no real cooldown rather the skill can be used as long as you have enough stamina. Skills using this won't ever be added to the cooldowns list

You can use https://github.com/lambdaclass/curse_of_mirra/pull/1590 to test, but not really necessary as nothing is added in that PR, rather you would need to add some debug lines

2024-03-14 21:57 UTC, manucamejo requested changes

2024-03-14 21:57 UTC, manucamejo commented on apps/arena/lib/arena/game_launcher.ex
> +  @clients_needed 1
Please, revert this!

2024-03-14 22:04 UTC, Nico-Sanchez requested changes
When a skill is on cooldown and I try to trigger it I lose control of my character.
I don't know if this should be fixed here or disable the button in the client.
Let's either fix it here or wait for a client PR that fixes this.

https://github.com/lambdaclass/mirra_backend/assets/65268603/ae77c46f-58b3-4063-80b2-22eadbe9d0b0

2024-03-15 15:17 UTC, manucamejo commented
> When a skill is on cooldown and I try to trigger it I lose control of my character. I don't know if this should be fixed here or disable the button in the client. Let's either fix it here or wait for a client PR that fixes this.
> Screen.Recording.2024-03-14.at.19.02.55.mov

I think that is a front end issue, @BertovDev can you check it?

2024-03-15 15:49 UTC, BertovDev commented
> > When a skill is on cooldown and I try to trigger it I lose control of my character. I don't know if this should be fixed here or disable the button in the client. Let's either fix it here or wait for a client PR that fixes this.
> > Screen.Recording.2024-03-14.at.19.02.55.mov
> 
> I think that is a front end issue, @BertovDev can you check it?

Sure! Fixing it in my PR in the client.

2024-03-15 17:16 UTC, AminArria commented on apps/arena/lib/arena/game_launcher.ex
> +  @clients_needed 1
Done

2024-03-15 17:23 UTC, AminArria commented on apps/arena/lib/arena/configuration.ex
> +    raise "Invalid Skill config for `#{skill_config[:name]}`: cooldown_mechanism or corresponding attribute is invalid"
Done

2024-03-15 19:15 UTC, Nico-Sanchez approved these changes

2024-03-18 16:11 UTC, manucamejo approved these changes

2024-03-18 16:20 UTC, agustinesco approved these changes
LGTM! 🪨

2024-03-18 16:21 UTC, merged