Refactir CampaignProgress to SuperCampaignProgress
lambdaclass/mirra_backend pull request #415
Opened 2024-03-25 17:52 UTC by lotuuu

2024-03-25 20:13 UTC, tkz00 requested changes
It would save the client a lot of trouble to include the campaignId alongside the levelId and superCampaignId in the super campaign progress. Currently, the search for campaignId is inefficient and adds unnecessary complexity to the client-side code.

2024-04-10 18:13 UTC, martinacantaro approved these changes
functional review approved!

2024-04-10 18:14 UTC, tkz00 approved these changes

2024-04-10 18:42 UTC, ncontinanza approved these changes
LGTM!

2024-04-10 18:51 UTC, merged