Rewrite battle tests
lambdaclass/mirra_backend pull request #427
Opened 2024-03-27 14:05 UTC by ncontinanza

2024-03-27 22:01 UTC, agustinesco approved these changes

2024-04-08 18:52 UTC, Nico-Sanchez requested changes
Looking good!
We could add some utils module or auxiliary functions to create the mocked schemas, we're defining several times a basic attack or a character that are almost the same but for 1 or 2 fields.

2024-04-09 19:02 UTC, Nico-Sanchez approved these changes

2024-04-09 19:02 UTC, Nico-Sanchez commented on apps/champions/mix.exs
> +  defp elixirc_paths(_), do: ["lib"]
Nice! 💎

2024-04-09 19:10 UTC, lotuuu approved these changes

2024-04-09 19:10 UTC, merged