Delete unused deploy script and generate protos
lambdaclass/mirra_backend pull request #469
Opened 2024-04-15 13:18 UTC by agustinesco

This pr fix two things:

The bot manager had an unused deploy script
The proto were generated with an old elixir version and there were some missing, this pr updates them

2024-04-15 15:08 UTC, Nico-Sanchez requested changes

2024-04-15 15:08 UTC, Nico-Sanchez commented on apps/bot_manager/lib/protobuf/messages.pb.ex
> +  field(:pools, 15, repeated: true, type: BotManager.Protobuf.GameState.PoolsEntry, map: true)
Hmmm you're pushing :pools from 14th to 15th position. Isn't that what we should avoid?

2024-04-15 15:08 UTC, Nico-Sanchez commented on apps/bot_manager/lib/protobuf/messages.pb.ex
> +defmodule BotManager.Protobuf.Player.CooldownsEntry do
What about the EffectsEntry?

2024-04-15 15:15 UTC, Nico-Sanchez approved these changes

2024-04-15 15:15 UTC, Nico-Sanchez commented on apps/bot_manager/lib/protobuf/messages.pb.ex
> +  field(:pools, 15, repeated: true, type: BotManager.Protobuf.GameState.PoolsEntry, map: true)
Answered in Slack. What happened is that the protobuf files generated by messages.proto file were outdated.
Just ran `make generate-protos` then pushed.

2024-04-15 15:15 UTC, Nico-Sanchez commented on apps/bot_manager/lib/protobuf/messages.pb.ex
> +defmodule BotManager.Protobuf.Player.CooldownsEntry do
Answered above.

2024-04-17 17:59 UTC, AminArria approved these changes

2024-04-17 18:00 UTC, merged