[GH-404] Allow to configure item radius size
lambdaclass/mirra_backend pull request #480
Opened 2024-04-16 19:30 UTC by agustinesco

Closes #404 

The item size wasn't accurate and it was not easily configurable, this pr will add the item size to the config file

2024-04-17 17:34 UTC, AminArria requested changes

2024-04-17 17:34 UTC, AminArria commented on apps/arena/priv/config.json
> +  },
Please move this into each item config

2024-04-17 21:25 UTC, agustinesco commented on apps/arena/priv/config.json
> +  },
Sounds good!

2024-04-18 18:57 UTC, agustinesco commented on apps/arena/priv/config.json
> +        "refresh_stamina": {}
this is happening in various prs, i think it's another issue with the formatter? 🤔

2024-04-19 20:13 UTC, Nico-Sanchez approved these changes

2024-04-19 20:13 UTC, merged