Rewrite Skills (Add Mechanics)
lambdaclass/mirra_backend pull request #495
Opened 2024-04-18 20:21 UTC by lotuuu

2024-04-24 20:31 UTC, martinacantaro submitted a review, later dismissed
Functional review approved. I did some random changes to the skills config and everything worked out fine.

2024-04-24 21:30 UTC, ncontinanza submitted a review, later dismissed

2024-04-26 15:08 UTC, Nico-Sanchez requested changes

2024-04-26 15:21 UTC, lotuuu commented on apps/champions/lib/champions/battle/simulator.ex
> +            {String.to_atom(key), value}
You're right, I'll look for an implementation where I parse the strings.

For the second one, the thing is that these `{key, value}` variables are from the map in `effects.type`, which has dynamic values, so I don't know if I can find a better alternative :/ what would you would change it to?

2024-04-26 18:13 UTC, Nico-Sanchez approved these changes

2024-04-26 18:24 UTC, ncontinanza approved these changes
LGTM!

2024-04-26 18:25 UTC, merged