Stat override message
lambdaclass/mirra_backend pull request #564
Opened 2024-05-03 17:45 UTC by ncontinanza

Part of https://github.com/lambdaclass/champions_of_mirra/issues/280

## Motivation

We should have a specific message for the case in which we want to override a stat's value, despite its current value.
In the immediate future this will be used to set the energy to 0 after casting the ultimate skill, in the near future it will be used to set other stats such as the health.

## Summary of changes

- Create a new StatOverride message.
- Send this message when casting a unit's ultimate skill, setting its energy to 0.

## How to test it?

You can use the SocketTester (remember to move it to the gateway directory) to simulate a battle and check that this new message is sent. You can follow these steps to do so:

```
IEx.configure(inspect: [limit: :infinity])
```

```
{:ok, user} = Champions.Users.register("Lotu")
```

```
campaign_progress = user.super_campaign_progresses |> hd()
```

```
{:ok, pid} = Gateway.SocketTester.start_link
```

```
Gateway.SocketTester.fight_level(pid, user.id, campaign_progress.level_id)
```

If you feel more comfortable using the client, start the client using [this branch](https://github.com/lambdaclass/champions_of_mirra/pull/420), go to BattleManager.cs and add a Debug.Log() in the PlayOutSteps() method, in the StatOverride case of the switch statement. Run a battle and there you should see how the frontend receives this new message when a unit is about to use the ulti.

## Checklist
- [X] Tested the changes locally.
- [X] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-07 19:41 UTC, lotuuu commented
Let's implement statoverrides for heal caps

2024-05-09 17:57 UTC, lotuuu requested changes

2024-05-09 17:57 UTC, lotuuu commented on apps/champions/lib/champions/battle/simulator.ex
> +      Map.put(
We're reducing the same list twice! Let's use a tuple as the accumulator, like `{new_history, new_state} = Enum.reduce(state.units, {history, state}, fn {_unit_id, unit} -> ...`

2024-05-09 20:45 UTC, lotuuu requested changes

2024-05-09 20:45 UTC, lotuuu commented on apps/champions/lib/champions/battle/simulator.ex
> +                  amount: -@ultimate_energy_cost
This should be 0, otehrwise the whole concept of stat_override doesn't make sense

2024-05-09 21:01 UTC, lotuuu approved these changes
To test with SocketTester:
```
IEx.configure(inspect: [limit: :infinity])
``
`

```
{:ok, user} = Champions.Users.register("Lotu")
```

```
campaign_progress = user.super_campaign_progresses |> hd()
```

```
{:ok, pid} = Gateway.SocketTester.start_link
```

```
Gateway.SocketTester.fight_level(pid, user.id, campaign_progress.level_id)
```

2024-05-09 21:25 UTC, ncontinanza commented
> To test with SocketTester:
> 
> ```
> IEx.configure(inspect: [limit: :infinity])
> ```
> 
> ```
> {:ok, user} = Champions.Users.register("Lotu")
> ```
> 
> ```
> campaign_progress = user.super_campaign_progresses |> hd()
> ```
> 
> ```
> {:ok, pid} = Gateway.SocketTester.start_link
> ```
> 
> ```
> Gateway.SocketTester.fight_level(pid, user.id, campaign_progress.level_id)
> ```

Nice! I'll add it to the description

2024-05-14 21:12 UTC, tkz00 approved these changes
Passed functional review!

2024-05-15 20:22 UTC, merged