[GH-429] Dungeon Settlement Levels
lambdaclass/mirra_backend pull request #593
Opened 2024-05-10 15:04 UTC by lotuuu

## Motivation

*Explain why not how.*
Closes #issue_number

## Summary of changes

*List your changes here.*

## How to test it?

*You can explain how you tested it or suggest a way to do so.*

## Checklist
- [ ] Tested the changes locally.
- [ ] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-13 16:29 UTC, ncontinanza requested changes

2024-05-13 16:29 UTC, ncontinanza commented on apps/gateway/test/champions_test.exs
> +      {:ok, user} = Users.register("KelineTreeAFKRewardsUser")
```suggestion
      {:ok, user} = Users.register("KalineTreeAFKRewardsUser")
```

2024-05-13 16:29 UTC, ncontinanza commented on apps/serialization/gateway.proto
> +    string id = 1;
This is unnecessary for the client (the KalineTreeLevel id as well)

2024-05-13 16:54 UTC, lotuuu commented on apps/champions/lib/champions/users.ex
> +  end
Done!

2024-05-13 16:54 UTC, lotuuu commented on apps/champions/lib/champions/users.ex
> +  defp calculate_afk_rewards(last_claim, afk_reward_rate) do
Done!

2024-05-13 19:42 UTC, lotuuu commented on apps/champions/lib/champions/users.ex
> +
This abstraction would require us to replace the Kaline Tree level up costs for currency_costs, which is a task that's outside the scope of this PR. It's also a beta feature. I'll create a ticket for it!

2024-05-13 21:29 UTC, ncontinanza approved these changes
LGTM!

2024-05-14 15:56 UTC, agustinesco commented on apps/game_backend/lib/game_backend/users.ex
> +  def level_up_dungeon_settlement(user_id, level_up_costs) do
Isn't this the same as `level_up_kaline_tree`? just changing the `increment_settlement_level`right?

2024-05-14 18:17 UTC, agustinesco approved these changes
LGTM! tested and the currencies can be claimed without issues 🪨

2024-05-14 18:17 UTC, merged