Gh 606 make pools damage crates
lambdaclass/mirra_backend pull request #610
Opened 2024-05-13 21:54 UTC by Nico-Sanchez

## Motivation

*Explain why not how.*
Closes #issue_number

## Summary of changes

*List your changes here.*

## How to test it?

*You can explain how you tested it or suggest a way to do so.*

## Checklist
- [ ] Tested the changes locally.
- [ ] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-15 14:23 UTC, tvillegas98 commented on apps/arena/lib/arena/game/effect.ex
> +        if entity.aditional_info.damage_immunity do
```suggestion
        if Map. has_key?(entity.aditional_info, :damage_immunity) do
```

If the entity doesn't have that key, the game crashes

2024-05-15 15:17 UTC, tvillegas98 approved these changes
The refactor looks good!

2024-05-15 15:41 UTC, agustinesco requested changes
Nice refactor!

I'm getting an error when i ult the crates with valtimer

```
** (KeyError) key :collides_with not found in: %{
lib/arena/game/effect.ex:223: Arena.Game.Effect.do_effect_mechanics/4
```

2024-05-15 16:50 UTC, Nico-Sanchez commented on apps/arena/lib/arena/game/effect.ex
> +        Entities.update_entity(entity, game_state)
You're right. Done!

2024-05-15 19:01 UTC, agustinesco requested changes
Valtimer ultimate isn't pulling people anymore

2024-05-15 21:23 UTC, Nico-Sanchez commented
> Valtimer ultimate isn't pulling people anymore

Fixed!

2024-05-15 21:51 UTC, agustinesco submitted a review, later dismissed
LGTM!

2024-05-15 22:20 UTC, manucamejo commented
@Nico-Sanchez please create the front-end PR

2024-05-15 22:21 UTC, manucamejo approved these changes

2024-05-15 22:26 UTC, manucamejo requested changes
If we are not using the effect in the front, we shouldn't add it to the messages.proto, please remove it.

2024-05-15 22:43 UTC, agustinesco approved these changes

2024-05-17 19:15 UTC, tvillegas98 approved these changes

2024-05-17 19:16 UTC, merged