428 dungeon implement buffs for dungeon
lambdaclass/mirra_backend pull request #632
Opened 2024-05-17 17:54 UTC by lotuuu

## Motivation

*Explain why not how.*
Closes #issue_number

## Summary of changes

*List your changes here.*

## How to test it?

*You can explain how you tested it or suggest a way to do so.*

## Checklist
- [ ] Tested the changes locally.
- [ ] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-27 21:23 UTC, ncontinanza requested changes

2024-05-27 22:06 UTC, ncontinanza requested changes

2024-05-27 22:06 UTC, ncontinanza commented on priv/repo/seeds.exs
> +            %{attribute: "health", magnitude: 1.05, operation: "Multiply"}
```suggestion
            %{attribute: "health", magnitude: 0.05, operation: "Multiply"}
```

2024-05-28 20:11 UTC, ncontinanza submitted a review, later dismissed

2024-05-29 15:41 UTC, agustinesco commented on apps/game_backend/lib/game_backend/users/upgrades/unlock_requirement.ex
We talked about this table and it represents a chain of upgrade dependencies, e.g. 
upgrade 2 --is locked behind --> upgrade 1 
So first you need to buy upgrade 1 to buy upgrade 2 

The thing is that it shared names with the table "unlocks" and it's a little bit misleading, maybe we could rename this table or the unlock table to make this clearer? also adding a comment into the "upgrade" table would help a lot

2024-05-29 16:35 UTC, lotuuu commented on apps/game_backend/lib/game_backend/users/upgrades/unlock_requirement.ex
Will do!

2024-05-29 17:13 UTC, agustinesco commented on apps/game_backend/lib/game_backend/units/skills/skill.ex
> +  alias GameBackend.Units.Buffs.Buff
This alias is wrong right? this module doesn't exists. The right one would be
`GameBackend.Users.Upgrades.Buff`

2024-05-29 17:17 UTC, agustinesco commented on apps/game_backend/lib/game_backend/users/upgrades/unlock_requirement.ex
The file name is missing

2024-05-29 19:42 UTC, agustinesco approved these changes
LGTM!

2024-05-29 19:58 UTC, ncontinanza approved these changes

2024-05-29 19:59 UTC, merged