[GH-463] fix to levels with costs
lambdaclass/mirra_backend pull request #677
Opened 2024-06-04 13:31 UTC by ncontinanza

## Motivation

*Explain why not how.*
Closes #issue_number

## Summary of changes

*List your changes here.*

## How to test it?

*You can explain how you tested it or suggest a way to do so.*

## Checklist
- [ ] Tested the changes locally.
- [ ] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-06-04 21:29 UTC, lotuuu requested changes

2024-06-04 21:29 UTC, lotuuu commented on priv/repo/seeds.exs
> +alias GameBackend.Users.Currencies.CurrencyCost
```suggestion
```

2024-06-04 21:47 UTC, lotuuu approved these changes

2024-06-05 19:59 UTC, agustinesco approved these changes
LGTM!

2024-06-05 19:59 UTC, merged