Gh 720 add game configuration
lambdaclass/mirra_backend pull request #722
Opened 2024-06-26 19:50 UTC by tvillegas98

## Motivation

*Explain why not how.*
Closes #issue_number

## Summary of changes

*List your changes here.*

## How to test it?

*You can explain how you tested it or suggest a way to do so.*

## Checklist
- [ ] Tested the changes locally.
- [ ] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-07-10 20:17 UTC, AminArria submitted a review, later dismissed
LGTM, do you have a plan on how to put the initial game configuration?

2024-07-11 18:20 UTC, tvillegas98 commented
> LGTM, do you have a plan on how to put the initial game configuration?

Maybe we should ran a function or a query that adds an initial configuration to the server

2024-07-15 09:13 UTC, AminArria submitted a review, later dismissed

2024-07-15 14:45 UTC, agustinesco requested changes
I think an encoder is missing, im having the following error when trying to run a match

2024-07-15 14:52 UTC, agustinesco commented on apps/game_backend/lib/game_backend/configuration.ex
> +    Repo.one(from(g in GameConfiguration, order_by: [desc: g.inserted_at]))
i think it will crash indeed, adding a `limit: 1 ` should do the trick

2024-07-15 14:53 UTC, tvillegas98 commented on apps/game_backend/lib/game_backend/configuration.ex
> +    Repo.one(from(g in GameConfiguration, order_by: [desc: g.inserted_at]))
Fair point, forgot to add a limit to that query

2024-07-15 14:53 UTC, tvillegas98 commented on apps/game_backend/lib/game_backend/configuration.ex
> +    Repo.one(from(g in GameConfiguration, order_by: [desc: g.inserted_at]))
Thanks for the heads up!

2024-07-15 14:54 UTC, tvillegas98 commented on apps/configurator/lib/configurator_web/controllers/game_configuration_html/edit.html.heex
> +  <:subtitle>Use this form to manage game_configuration records in your database.</:subtitle>
These templates were generated by phoenix so part of the stuff was not added by me, I say that's not necessary too

2024-07-15 14:54 UTC, tvillegas98 commented on apps/arena/lib/arena/configuration.ex
> +      Finch.build(:get, "#{gateway_url}/curse/configuration/characters", [{"content-type", "application/json"}])
That would be a good addon!

2024-07-15 14:57 UTC, agustinesco commented on apps/configurator/lib/configurator_web/controllers/game_configuration_html/edit.html.heex
> +  <:subtitle>Use this form to manage game_configuration records in your database.</:subtitle>
ooooh okey, i didn't knew they were auto generated

2024-07-15 15:32 UTC, AminArria approved these changes

2024-07-15 15:59 UTC, agustinesco approved these changes
LGTM! tested editing and creating a new configuration and it worked like a charm! one thing that i noticed is that we can deleted every config, maybe this could be an issue in the future but let's tackle this in a new interation.
Also remember to run the query to insert the first game config in the db when this is deployed to the servers

2024-07-15 16:05 UTC, AminArria approved these changes

2024-07-15 16:05 UTC, merged