[GH-730] Add match timeout
lambdaclass/mirra_backend pull request #731
Opened 2024-06-28 17:28 UTC by agustinesco

## Motivation

Every time you created a quick game and left the match it'll run indefinitely since the zone isn't enabled

Closes #730

## Summary of changes

Added timeout message

## How to test it?

start a quick game match and wait 5 minutes (you can reduce this time in the config)

## Checklist
- [x] Tested the changes locally.
- [x] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-07-02 18:47 UTC, tvillegas98 requested changes
Works well! Left you a comment regarding the time unit we're using

2024-07-02 18:47 UTC, tvillegas98 commented on apps/arena/priv/config.json
> +    "match_timeout_minutes": 5
I prefer to convert this into milliseconds to maintain consistency with the other time parameters

2024-07-03 21:49 UTC, tvillegas98 approved these changes
Great job! @agustinesco

2024-07-04 21:34 UTC, tvillegas98 approved these changes

2024-07-05 16:17 UTC, manucamejo approved these changes

2024-07-05 16:18 UTC, merged