Gh 822 add google oauth to configurator
lambdaclass/mirra_backend pull request #825
Opened 2024-07-31 22:42 UTC by Nico-Sanchez

## Motivation

*Explain why not how.*
Closes #issue_number

## Summary of changes

*List your changes here.*

## How to test it?

*You can explain how you tested it or suggest a way to do so.*

## Checklist
- [ ] Tested the changes locally.
- [ ] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-08-05 22:09 UTC, agustinesco requested changes
I can log in using the correct credentials! but i can't go anywhere i can just acces the home page

2024-08-06 17:53 UTC, AminArria approved these changes

2024-08-06 17:53 UTC, AminArria commented on config/runtime.exs
> +  client_id: System.get_env("CONFIGURATOR_GOOGLE_CLIENT_ID"),
We can deal with it once it pops up again (or maybe ignore it for ever), but this likely breaking game client google sign in

2024-08-06 19:17 UTC, AminArria approved these changes

2024-08-06 21:14 UTC, agustinesco approved these changes
LGTM!

2024-08-06 21:15 UTC, merged