[GH-852] Configurator: Migrate effects config
lambdaclass/mirra_backend pull request #856
Opened 2024-08-12 22:12 UTC by agustinesco

## Motivation

Keep migrating fields from config.json to configurator app

Part of https://github.com/lambdaclass/mirra_backend/issues/852

## Summary of changes

- Added embedded schema Effect to be shared across distinct structs
- Adapted in game effects to work with a field instead of looking for effects in the game config
- Added show and edit of effects to configurator app

## How to test it?

Start a match and everything should keep working as before

## Checklist
- [x] Tested the changes locally.
- [x] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-08-27 18:31 UTC, tvillegas98 submitted a review, later dismissed
LGTM

2024-09-02 15:28 UTC, tvillegas98 approved these changes

2024-09-05 17:41 UTC, tvillegas98 approved these changes

2024-09-09 16:56 UTC, AminArria requested changes
Not sure where/how, but the Valtimer dash is broken

Stacktrace
```
[error] GenServer #PID<0.1554.0> terminating
** (KeyError) key :execute_multiple_times not found in: {:damage_immunity, %{effect_delay_ms: 0, execute_multiple_times: false}}

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (arena 0.7.1) lib/arena/game/effect.ex:158: anonymous fn/5 in Arena.Game.Effect.apply_effect_mechanic/3
    (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
    (elixir 1.16.1) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (arena 0.7.1) lib/arena/game/effect.ex:143: anonymous fn/2 in Arena.Game.Effect.apply_effect_mechanic_to_entities/1
    (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
    (arena 0.7.1) lib/arena/game_updater.ex:259: Arena.GameUpdater.handle_info/2
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

2024-09-12 15:52 UTC, tvillegas98 submitted a review, later dismissed

2024-09-12 17:55 UTC, AminArria submitted a review, later dismissed

2024-09-12 17:59 UTC, AminArria approved these changes

2024-09-12 18:04 UTC, tvillegas98 approved these changes

2024-09-12 18:04 UTC, merged