[GH-814] Add meta quests
lambdaclass/mirra_backend pull request #875
Opened 2024-08-20 22:45 UTC by agustinesco

## Motivation

We need to include a new kind of quest called "meta", the progress for this quest isn't accumulated by matches but by completed quests in the same day as the date of creation of the meta quest

Closes #814

## Summary of changes

- Added  "meta" quest type
- Generate meta quests alongside daily quests
- Change `get_user_quest_progress` to handle meta quests differently

## How to test it?

- Enter the game as a guest in Unity and copy the user_id:
<img width="664" alt="Captura de pantalla 2024-07-24 a la(s) 5 10 15 p  m" src="https://github.com/user-attachments/assets/bef03a34-20ce-4220-8227-5b1f11ac6d03">

- Get to see if he has any quest
`curl -X GET  http://localhost:4001/curse/users/user_id`

- Play a match in unity and lose 

- if you run the get endpoint again you should see that the quest has some progress depending on your actions in the match, there's a quest that you need to lose a match to complete, copy that quest "id" field and run the following command:
`curl -X GET  http://localhost:4001/curse/users/user_id/quest/quest_id/complete_quest`

- Get the user and check that the quest is finished and a new quest turn actives, this means that it has a value in `activated_at`
`curl -X GET  http://localhost:4001/curse/users/user_id`

The meta quest should have some progress

## Checklist
- [ ] Tested the changes locally.
- [ ] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-08-29 19:26 UTC, alfopisano submitted a review, later dismissed
Nice!! Tested locally and on my iOS device

2024-08-29 19:27 UTC, alfopisano reviewed
Ignore the previous approve, it was intended to be on the client PR

2024-08-30 20:08 UTC, Nico-Sanchez requested changes

2024-08-30 20:08 UTC, Nico-Sanchez commented on apps/game_backend/lib/game_backend/curse_of_mirra/quests.ex
> +      if user_quest.status == "available" && Quests.completed_quest?(user_quest, user.arena_match_results, user) do
Let's just send the user and get the arena_match_results there?

2024-08-30 20:08 UTC, Nico-Sanchez commented on apps/game_backend/lib/game_backend/users.ex
> +            user_quest.status == "completed" && Date.diff(date, NaiveDateTime.to_date(user_quest.inserted_at)) == 0 &&
I think we should use `and` instead of `&&`

2024-08-30 20:08 UTC, Nico-Sanchez commented on apps/game_backend/lib/game_backend/users.ex
> +      |> hd()
```suggestion
      |> Enum.random()
```

2024-08-30 20:08 UTC, Nico-Sanchez commented on apps/game_backend/lib/game_backend/users.ex
> +            user_quest.quest.type == :meta && Date.diff(date, NaiveDateTime.to_date(user_quest.inserted_at)) == 0
```suggestion
            user_quest.quest.type == :meta and Date.diff(date, NaiveDateTime.to_date(user_quest.inserted_at)) == 0
```

2024-08-30 20:08 UTC, Nico-Sanchez commented on apps/game_backend/lib/game_backend/curse_of_mirra/quests.ex
> +      NaiveDateTime.diff(user_quest.inserted_at, meta_quest.inserted_at, :day) == 0 && user_quest.status == "completed" &&
```suggestion
      NaiveDateTime.diff(user_quest.inserted_at, meta_quest.inserted_at, :day) == 0 and user_quest.status == "completed" and
```

2024-08-30 20:08 UTC, Nico-Sanchez commented on apps/game_backend/lib/game_backend/curse_of_mirra/quests.ex
> +      if user_quest.status == "available" && Quests.completed_quest?(user_quest, user.arena_match_results, user) do
```suggestion
      if user_quest.status == "available" and Quests.completed_quest?(user_quest, user.arena_match_results, user) do
```

2024-09-03 15:56 UTC, agustinesco commented on apps/game_backend/lib/game_backend/curse_of_mirra/quests.ex
> +      NaiveDateTime.diff(user_quest.inserted_at, meta_quest.inserted_at, :day) == 0 && user_quest.status == "completed" &&
Sure! i think it's a better name too

2024-09-03 15:56 UTC, agustinesco commented on apps/game_backend/lib/game_backend/users.ex
> +      |> hd()
😅

2024-09-03 15:57 UTC, agustinesco commented on apps/game_backend/lib/game_backend/curse_of_mirra/quests.ex
> +      NaiveDateTime.diff(user_quest.inserted_at, meta_quest.inserted_at, :day) == 0 && user_quest.status == "completed" &&
done

2024-09-03 15:57 UTC, agustinesco commented on apps/game_backend/lib/game_backend/curse_of_mirra/quests.ex
> +      if user_quest.status == "available" && Quests.completed_quest?(user_quest, user.arena_match_results, user) do
done

2024-09-03 16:44 UTC, Nico-Sanchez approved these changes

2024-09-04 17:44 UTC, tvillegas98 approved these changes
Great work!

2024-09-04 17:45 UTC, merged