Add randomness to the spikes behaviour
lambdaclass/mirra_backend pull request #889
Opened 2024-08-29 11:40 UTC by manucamejo

## Motivation

All the spikes were moving together, we needed to add some randomness.

## Summary of changes

The next status depends on the value set on the ConfiguratorApp and a random value also depending on that value.

## How to test it?

See if the spikes are spawning and hiding separately.

## Checklist
- [ ] Tested the changes locally.
- [ ] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-08-29 13:28 UTC, agustinesco submitted a review, later dismissed
LGTM!

2024-08-30 14:11 UTC, Nico-Sanchez requested changes
Doing this we lose the constant time between spike transitions, which we learn through a game to make decisions.
Also, the 'randomness range list' could be just a coefficient in the configurator (randomness coefficient).

We can merge it as it is, but I want to know if we took all this into account and to create the respective issues if what I said brings something new to the table.

2024-08-30 14:11 UTC, Nico-Sanchez commented on apps/arena/lib/arena/game/obstacle.ex
> +          next_status_params.time_until_transition_ms,
Isn't this just...
```suggestion
          time_until_transition_ms,
```

2024-08-30 14:12 UTC, manucamejo commented
Nico you are right, let's merge it and create the issue please.

2024-08-30 18:25 UTC, agustinesco approved these changes

2024-08-30 18:25 UTC, merged