Make central configurable for arena
lambdaclass/mirra_backend pull request #909
Opened 2024-09-11 14:47 UTC by Nico-Sanchez

## Motivation

Closes #920 
We can edit gateway_url in configurator but Arena's server never notices about this change.

## Summary of changes

- [Add post endpoint in arena to update gateway url](https://github.com/lambdaclass/mirra_backend/commit/07b1b7af711eed66fb32dc459d54a1e072079d28)
- [Make post request to update arena's gateway_url at arena_server creation and update](https://github.com/lambdaclass/mirra_backend/commit/894586f1b833598d76ebb8f5d6bd1720aefcf61c)

## How to test it?

Create a new server or update a current one in configurator.
Then, set/update its gateway_url. Now that arena should point to that central.
You can check by connecting to ssh to that server or just play a game and see what config it takes.

## Checklist
- [x] Tested the changes locally.
- [x] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-09-11 21:59 UTC, agustinesco requested changes

2024-09-11 21:59 UTC, agustinesco commented on apps/configurator/lib/configurator_web/controllers/arena_server_controller.ex
> +  defp update_arena_gateway_url(_former_url, new_url, arena_url) do
Can we add an `if env != dev` here? i think this will cause chaos

2024-09-11 21:59 UTC, agustinesco commented on apps/configurator/lib/configurator_web/controllers/arena_server_controller.ex
> +  defp update_arena_gateway_url(former_url, former_url, _arena_url), do: nil
god

2024-09-12 14:29 UTC, Nico-Sanchez commented on apps/configurator/lib/configurator_web/controllers/arena_server_controller.ex
> +  defp update_arena_gateway_url(former_url, former_url, _arena_url), do: nil
Godardium

2024-09-12 15:29 UTC, agustinesco approved these changes
LGTM! tested deploying servers and it's being updated correctly

2024-09-12 16:00 UTC, merged